packages:
  - packages/*

catalogs:
  cli:
    '@antfu/eslint-config': ^4.10.1
    bumpp: ^10.1.0
    eslint: ^9.22.0
    lint-staged: ^15.5.0
    simple-git-hooks: ^2.11.1
    tsx: ^4.19.3
    unbuild: ^3.5.0
  compiler:
    '@vue/compiler-sfc': ^3.5.18
    typescript: ^5.8.2
  testing:
    '@unocss/cli': ^66.4.2
    '@unocss/vite': ^66.4.2
    '@vitejs/plugin-vue': ^6.0.1
    unocss: ^66.4.2
    vite: ^7.1.1
    vitest: ^3.0.8
    vue: ^3.5.18
  types:
    '@types/node': ^22.13.10
    '@unocss/core': ^66.4.2

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
